version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'
  app:
    image: node-backend
    volumes:
      - .:/app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo